version: '3'

services:
  postgres:
    image: docker.io/postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-db}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_USER: "${POSTGRES_USER:-dbuser}"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - "./bin:/usr/local/lab/bin"
      - "./migrations:/usr/local/lab/migrations"
