version: '3'

services:
  d2:
    build:
      context: ./docker/d2
    command: ./build-diagrams.sh -d 1
    volumes:
      - "./diagrams:/usr/src/app/input"
      - "./output:/usr/src/app/output"
  plantuml:
    image: docker.io/plantuml/plantuml-server:jetty
    ports:
      - "8080:8080"
  postgres:
    image: docker.io/postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-db}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_USER: "${POSTGRES_USER:-dbuser}"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - "./bin:/usr/local/lab/bin"
      - "./migrations:/usr/local/lab/migrations"
